import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
                
                <div className="flex gap-7">

                    <div >
                        <Sidebar />
                    </div>
                    <div>
                        {children}
                    </div>
                </div>
        </div>
    );
}