import type { Metadata } from "next";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <div className="flex gap-7">

                    <div >
                        <Sidebar />
                    </div>
                    <div>
                        {children}
                    </div>
                </div>

            </body>
        </html>
    );
}